name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install package
      run: |
         npm install 
         cd api
         npm install
         cd ..
         
    - name: Generate Docs
      run: |
          npm run generate
          cd api
          npm run generate
          cd .. 

